apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
stringData:
  DB_PASSWORD: "example"
  EMAIL_HOST_USER: "youremail@example.com"
  EMAIL_HOST_PASSWORD: "<your email password>"
  SECRET_KEY: "<your_secret_key>"
